base_channels: 8
class_weights: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYDQAAADE5NjYzOTkxODUzMjhxAlgDAAAAY3B1cQNLIE50cQRRLoACXXEAWA0AAAAxOTY2
    Mzk5MTg1MzI4cQFhLiAAAAAAAAAAAAAAP6uqqj6MLro9OY7jPQAAgD2rqqo+AACAPgAAAD8AAIA+
    AAAAP6uqqj7ZiZ09AAAAPs3MzD0AAIA+iYiIPQAAgD6rqio+q6qqPgAAAD+rqqo+AAAAP9mJnT3N
    zEw+jC66PQAAAD+rqio+JUkSPjmO4z3NzEw+zczMPTmO4z0=
- 0
- !!python/tuple
  - 32
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
in_channels: 128
kernel_size: 3
learning_rate: 0.001
n_max_pool: 1
n_res_blocks: 4
num_classes: 32
