name: torch_cuda
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - absl-py=2.1.0
  - anyio=4.3.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=23.2.0
  - aws-c-auth=0.7.16
  - aws-c-cal=0.6.10
  - aws-c-common=0.9.13
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.4
  - aws-c-mqtt=0.10.2
  - aws-c-s3=0.5.1
  - aws-c-sdkutils=0.1.15
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.2
  - aws-sdk-cpp=1.11.267
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - blas=2.121
  - blas-devel=3.9.0
  - bleach=6.1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.26.0
  - ca-certificates=2024.6.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2024.6.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.2.0
  - cuda-cccl=12.3.101
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=12.3.101
  - cuda-runtime=11.8.0
  - cudatoolkit=11.8.0
  - cycler=0.12.1
  - debugpy=1.8.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - filelock=3.13.1
  - fonttools=4.49.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - fsspec=2024.3.1
  - gettext=0.21.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - gst-plugins-base=1.22.9
  - gstreamer=1.22.9
  - h11=0.14.0
  - h2=4.1.0
  - h5py=3.11.0
  - hdf5=1.14.3
  - hpack=4.0.0
  - httpcore=1.0.4
  - httpx=0.27.0
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.6
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - importlib_resources=6.1.1
  - intel-openmp=2024.0.0
  - ipykernel=6.29.2
  - ipython=8.22.0
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.3
  - joblib=1.3.2
  - json5=0.9.17
  - jsonpointer=2.4
  - jsonschema=4.21.1
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.21.1
  - jupyter-lsp=2.2.2
  - jupyter_client=8.6.0
  - jupyter_core=5.7.1
  - jupyter_events=0.9.0
  - jupyter_server=2.12.5
  - jupyter_server_terminals=0.5.2
  - jupyterlab=4.1.2
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.25.3
  - keras=3.3.3
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20230802.1
  - libaec=1.1.3
  - libarrow=15.0.0
  - libarrow-acero=15.0.0
  - libarrow-dataset=15.0.0
  - libarrow-flight=15.0.0
  - libarrow-flight-sql=15.0.0
  - libarrow-gandiva=15.0.0
  - libarrow-substrait=15.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcrc32c=1.1.2
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.4.107
  - libcurand-dev=10.3.4.107
  - libcurl=8.5.0
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.19
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libglib=2.78.4
  - libgoogle-cloud=2.17.0
  - libgoogle-cloud-storage=2.17.0
  - libgrpc=1.60.1
  - libhwloc=2.9.3
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libogg=1.3.4
  - libparquet=15.0.0
  - libpng=1.6.42
  - libprotobuf=4.25.1
  - libre2-11=2023.06.02
  - libsodium=1.0.18
  - libsqlite=3.45.1
  - libssh2=1.11.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libuv=1.47.0
  - libvorbis=1.3.7
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.12.5
  - libzlib=1.2.13
  - lightning=2.2.3
  - lightning-utilities=0.11.2
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib=3.8.3
  - matplotlib-base=3.8.3
  - matplotlib-inline=0.1.6
  - mdurl=0.1.2
  - mistune=3.0.2
  - mkl=2024.0.0
  - mkl-devel=2024.0.0
  - mkl-include=2024.0.0
  - ml_dtypes=0.4.0
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - namex=0.0.8
  - nbclient=0.8.0
  - nbconvert-core=7.16.1
  - nbformat=5.9.2
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - notebook-shim=0.2.4
  - numpy=1.26.4
  - openjpeg=2.5.0
  - openssl=3.3.1
  - optree=0.11.0
  - orc=1.9.2
  - overrides=7.7.0
  - packaging=23.2
  - pandas=2.2.0
  - pandocfilters=1.5.0
  - parso=0.8.3
  - patsy=0.5.6
  - pcre2=10.42
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=24.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.0
  - ply=3.11
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pure_eval=0.2.2
  - pyarrow=15.0.0
  - pycparser=2.21
  - pygments=2.17.2
  - pyparsing=3.1.1
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - python=3.11.8
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.19.1
  - python-json-logger=2.0.7
  - python-tzdata=2024.1
  - python_abi=3.11
  - pytorch=2.2.1
  - pytorch-cuda=11.8
  - pytorch-lightning=2.3.0
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pywin32=306
  - pywinpty=2.0.12
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qt-main=5.15.8
  - re2=2023.06.02
  - referencing=0.33.0
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.7.1
  - rpds-py=0.18.0
  - scikit-learn=1.4.1.post1
  - scipy=1.12.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.2
  - setuptools=69.1.0
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.3.0
  - soupsieve=2.5
  - stack_data=0.6.2
  - statsmodels=0.14.2
  - sympy=1.12
  - tbb=2021.11.0
  - terminado=0.18.0
  - threadpoolctl=3.3.0
  - tinycss2=1.2.1
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - torchmetrics=1.3.2
  - tornado=6.4
  - tqdm=4.66.2
  - traitlets=5.14.1
  - types-python-dateutil=2.8.19.20240106
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - typing_utils=0.1.0
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - uri-template=1.3.0
  - urllib3=2.2.1
  - vc=14.3
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - wcwidth=0.2.13
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.7.0
  - wheel=0.42.0
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zstd=1.5.5
  - pip:
      - audioread==3.0.1
      - grpcio==1.63.0
      - lazy-loader==0.4
      - librosa==0.10.1
      - llvmlite==0.42.0
      - markdown==3.6
      - msgpack==1.0.8
      - numba==0.59.1
      - pooch==1.8.1
      - protobuf==5.26.1
      - soundfile==0.12.1
      - soxr==0.3.7
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - torchaudio==2.2.1
      - torchvision==0.17.1
      - werkzeug==3.0.2
